### ISSUE TITLE
"Subroutine Mojo::UserAgent::Cached::getcwd redefined" error on load

### ISSUE THREAD

**Issue by anirvan** [nicomen/mojo-useragent-cached#3]
When I use Mojo::UserAgent::Cached version 1.16, I always get an immediate `Subroutine Mojo::UserAgent::Cached::getcwd redefined at …/Mojo/UserAgent/Cached.pm line 21` warning.

It looks like both `POSIX` and `Cwd` export a `getcwd` function, causing the error message.

Could you prevent the redefine by using only the items needed?

For example, `use POSIX ('O_WRONLY', 'O_APPEND', 'O_CREAT')` might fix the issue.

Thanks!

**Comment by nicomen** [comment]
Thanks, should be fixed in 1.17
