### ISSUE TITLE
Has started failing

### ISSUE THREAD

**Issue by toreau** [nicomen/mojo-useragent-cached#4]
Ref. http://www.cpantesters.org/cpan/report/6c7b28f6-11a9-11ec-857d-71a57377d7c7

**Comment by nicomen** [comment]
Thanks for the report, haven't been able to upgrade to Mojolicious 9.x in existing projects due to tthe big routing breakage, but triaging now it seems this broke in Mojolicious 9.20 after introduction of TRACE error level. A fix should be out momentarily in 1.18
